#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="i3"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES

# Execute all files in scripts directory
if [[ -d "$DOTFILES/scripts" ]]; then
    for script in "$DOTFILES"/scripts/*; do
        if [[ -f "$script" ]]; then
            chmod +x "$script"  # Ensure file is executable
            "$script"
        fi
    done
fi
